[package]
name = "ferr-os"
version = "0.1.0"
edition = "2021"
authors = ["soohoonchoi@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"